apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

group = 'com.nischayk3.spinzoops.overlay'
version = '1.0.0'

def safeExtGet(prop, fallback) {
    rootProject.ext.has(prop) ? rootProject.ext.get(prop) : fallback
}

android {
    compileSdkVersion safeExtGet("compileSdkVersion", 35)
    namespace "com.nischayk3.spinzoops.overlay"

    defaultConfig {
        minSdkVersion safeExtGet("minSdkVersion", 24)
        targetSdkVersion safeExtGet("targetSdkVersion", 35)
        versionCode 1
        versionName "1.0.0"
    }

    lintOptions {
        abortOnError false
    }
}

dependencies {
    implementation project(':expo-modules-core')
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:${safeExtGet('kotlinVersion', '1.9.24')}"
    implementation 'com.google.firebase:firebase-messaging:24.1.0'
    implementation 'androidx.core:core-ktx:1.15.0'
}
